ignored = ["local/*"]

required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen"
]

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/gardener/controller-manager-library"
  branch = "master"

[[constraint]]
  name = "github.com/aliyun/alibaba-cloud-sdk-go"
  version = "1.60.33"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v24.1.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.19.41"

[[constraint]]
  name = "google.golang.org/api"
  version = "v0.1.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.4"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.4"

[[constraint]]
  name = "github.com/gophercloud/gophercloud"
  version = "v0.2.0"

# Dependencies for testing purposes only
[[constraint]]
  name = "github.com/onsi/gomega"
  version = "v1.5.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "v1.8.0"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "v1.1.4"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
