apiVersion: v1
kind: Secret
metadata:
  name: netlify-credentials
  namespace: default
type: Opaque
data:
  # replace '...' with values encoded as base64
  # Use a Netlify Personal Access Token:
  # https://docs.netlify.com/accounts-and-billing/user-settings/#connect-with-other-applications
  # For details see https://github.com/gardener/external-dns-management/blob/master/docs/cloudflare/README.md#using-the-api-token
  NETLIFY_API_TOKEN: ...
    # Alternatively use Gardener cloud provider credentials convention
  #apiToken: ...
