apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: default
type: Opaque
data:
  # replace '...' with the API Key generated. The token should have permission of Zone:Read and DNS:Edit for all zones.
  # You can optionally exclude certain zones
  # see https://support.cloudflare.com/hc/en-us/articles/200167836-Managing-API-Tokens-and-Keys
  CLOUDFLARE_API_TOKEN: ...
