# For details see https://github.com/SayakMukhopadhyay/external-dns-management/blob/master/doc/cloudflare/README.md
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider
metadata:
  name: cloudflare
  namespace: default
spec:
  type: cloudflare-dns
  secretRef:
    name: cloudflare-credentials
  domains:
    include:
    - my.own.domain.com
