apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: referencing
  namespace: default
spec:
  dnsName: "referencing.ringtest.dev.k8s.ondemand.com"
  # references DNSEntry defined in 40-entry-dns.yaml
  # i.e. applies specified target/text with another dnsName
  reference:
    name: dns
    namespace: default
